# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='input_tax',
            new_name='input_gst',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='output_tax',
            new_name='output_gst',
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
